"""social

Revision ID: 38a4f934dc2a
Revises: bc96f71a7d15
Create Date: 2022-12-06 23:04:46.872785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '38a4f934dc2a'
down_revision = 'bc96f71a7d15'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
