"""remove social

Revision ID: 819bb7d07a5d
Revises: 2a6e9045634e
Create Date: 2022-12-08 15:44:02.146597

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '819bb7d07a5d'
down_revision = '2a6e9045634e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('from_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('to_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['user.id'], name='social_from_id_fkey'),
    sa.ForeignKeyConstraint(['to_id'], ['user.id'], name='social_to_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='social_pkey')
    )
    # ### end Alembic commands ###
