"""ajusta o banco

Revision ID: c2b5d3b376fb
Revises: 819bb7d07a5d
Create Date: 2022-12-13 17:09:36.770686

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c2b5d3b376fb'
down_revision = '819bb7d07a5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
